### ISSUE TITLE
AI required

### ISSUE THREAD

**Issue by flatmax** [madChopsCoderAu/seriously#5]
Hey can someone make an AI to auto invite all pull requesters ?

**Comment by MichaelZaporozhets** [comment]
Do you realise that this is the exact reason everyone got so pissed off at you to start with?

**Comment by MichaelZaporozhets** [comment]
Is this some kind of performance art piece?

**Comment by flatmax** [comment]
If someone forks seriously and pushes asking us to pull here, should we report them for lodging a pull request ? OR should we invite them in ?

I don't know them ... in fact whats worse ... they might not even be part of our graph.
So if they aren't part of our graph and they don't know any of us ... this is a serious infliction on our human rights ...

It would be the equivalent of us walking down the street and someone saying hello ... randomly.

Worse it would be the equivalent of someone walking down the street giving me someone my own flyer slightly changed back and asking me to give it to everyone else ...

**Comment by jcro21** [comment]
They might not even be part of our graph?! That's too terrible to contemplate.

**Comment by Maikuolan** [comment]
I would not recommend automating invites. Grey area, but if someone wanted to come down on you for it and needed an excuse, it could arguably be against the [GitHub ToS](https://help.github.com/articles/github-terms-of-service/):

> ### 2. Account Requirements
> We have a few simple rules for accounts on GitHub's Service.
>
> - You must be a human to create an account. Accounts registered by "bots" or other automated methods are not permitted. We do permit machine accounts:
> - A machine account is an account set up by an individual human who accepts the Terms on behalf of the account, provides a valid email address, and is responsible for its actions. A machine account is used exclusively for performing automated tasks. Multiple users may direct the actions of a machine account, but the owner of the account is ultimately responsible for the machine's actions. You may maintain no more than one free machine account in addition to your free personal account.

Sending invites requires an account. Automated invites = Automated task, ergo, by definition of their ToS, any account doing it could be described as a "machine account" or "bot", which they don't permit, Whoever's responsible for building such a thing, would likely be held responsible for any consequences of it operating, thus, having their accounts revoked, email addresses blacklisted or whatever else.

GitHub staff seem pretty cool from my past experiences with them, and I've not yet had any problems with them regarding what I have or haven't done at GitHub before. They've always been very friendly, helpful, and generous. However, that all said, common sense prevails, and I wouldn't want to risk doing anything that might piss them off.

**Comment by flatmax** [comment]
Point taken, that is great information, thanks.

I think I'll close this automation issue.
